[version]
current = "0.1.3"
regex = '''(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'''

[git]
tag_template = "v{new_version}"
message_template = "release: v{new_version}"

[[file]]
src = "version.txt"

[[file]]
src = "pixi.toml"

[[file]]
src = "demo/Doxyfile"
search = 'PROJECT_NUMBER         = "{current_version}"'

[[file]]
src = "demo/src/yoda.hpp"
search = '@version {current_version}'

[[file]]
src = "action.yml"
search = 'default: "{current_version}"'
